# Generated by Django 5.2.1 on 2025-05-31 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Contacto"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono del contacto de emergencia.",
                        max_length=20,
                        verbose_name="Número de Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Hijo, Amigo, Familiar.",
                        max_length=100,
                        verbose_name="Relación",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si este es el contacto principal para notificaciones SOS.",
                        verbose_name="Contacto Principal",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de Emergencia",
                "verbose_name_plural": "Contactos de Emergencia",
                "ordering": ["user", "-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="KnownPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Persona"
                    ),
                ),
                (
                    "face_encoding",
                    models.TextField(
                        blank=True,
                        help_text="Representación vectorial de la cara para reconocimiento.",
                        verbose_name="Codificación Facial",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Familiar, Amigo, Colega.",
                        max_length=100,
                        verbose_name="Relación",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas Adicionales"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_persons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Conocida",
                "verbose_name_plural": "Personas Conocidas",
                "ordering": ["user", "name"],
            },
        ),
    ]
