# Generated by Django 5.2.1 on 2025-06-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        help_text="Identificador único para la consulta cacheada",
                        max_length=255,
                        unique=True,
                        verbose_name="Clave de caché",
                    ),
                ),
                (
                    "cache_data",
                    models.JSONField(
                        help_text="Respuesta de la API almacenada en formato JSON",
                        verbose_name="Datos cacheados",
                    ),
                ),
                (
                    "expiry_time",
                    models.DateTimeField(
                        help_text="Momento en que el caché expira",
                        verbose_name="Hora de expiración",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Caché de API",
                "verbose_name_plural": "Cachés de API",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_transport",
                    models.CharField(
                        choices=[
                            ("walking", "A pie"),
                            ("cycling", "Bicicleta"),
                            ("public_transport", "Transporte público"),
                            ("car", "Coche"),
                        ],
                        default="walking",
                        max_length=20,
                        verbose_name="Medio de transporte preferido",
                    ),
                ),
                (
                    "max_walking_distance",
                    models.IntegerField(
                        default=500,
                        help_text="Distancia máxima que está dispuesto a caminar",
                        verbose_name="Distancia máxima a pie (metros)",
                    ),
                ),
                (
                    "voice_speed",
                    models.CharField(
                        choices=[
                            ("slow", "Lenta"),
                            ("normal", "Normal"),
                            ("fast", "Rápida"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Velocidad de voz",
                    ),
                ),
                (
                    "include_accessibility_info",
                    models.BooleanField(
                        default=True,
                        help_text="Si incluir automáticamente información de accesibilidad en las respuestas",
                        verbose_name="Incluir información de accesibilidad",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencias de Usuario",
                "verbose_name_plural": "Preferencias de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="VoiceQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("parada_cercana", "Parada más cercana"),
                            ("calculo_ruta", "Cálculo de ruta"),
                            ("estado_trafico", "Estado del tráfico"),
                            ("info_accesibilidad", "Información de accesibilidad"),
                            ("general", "Consulta general"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de consulta",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(
                        help_text="Texto obtenido del reconocimiento de voz",
                        verbose_name="Texto original (STT)",
                    ),
                ),
                (
                    "response_text",
                    models.TextField(
                        help_text="Texto de respuesta antes de TTS",
                        verbose_name="Respuesta generada",
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        help_text="Tiempo total desde STT hasta TTS",
                        verbose_name="Tiempo de procesamiento (segundos)",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="Consulta exitosa"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitud de consulta"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitud de consulta"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de consulta"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta de Voz",
                "verbose_name_plural": "Consultas de Voz",
                "ordering": ["-created_at"],
            },
        ),
    ]
